name: Cancel on close
on:
  pull_request:
    types: [closed]
permissions: {}
jobs:
  cancel-on-close:
    permissions:
      actions: write
    uses: dryvist/.github/.github/workflows/_cancel-on-close.yml@0aab1ddaecacea5dc9752b075e2ac10491af33bf # v1.11.3
