name: Cancel on close
on:
  pull_request:
    types: [closed]
permissions: {}
jobs:
  cancel-on-close:
    permissions:
      actions: write
    uses: dryvist/.github/.github/workflows/_cancel-on-close.yml@10af73f872e043e91ff6327d0ef2548881f61298 # v1.11.2
